import concurrent.futures
import json
import textwrap
import uuid
from typing import List, Dict

from dotenv import load_dotenv, find_dotenv

from api.ai.assistants import ArbiterAssistantDecorator, PlayerAssistantDecorator, RawAssistant
from api.models import Player, Game, ArbiterReply
from api.player_generator import generate_players
from api.redis.redis_helper import connect_to_redis, save_game_to_redis, load_game_from_redis, \
    add_player_messages_to_redis_list, delete_redis_game_history_list, read_messages_from_redis, delete_game_from_redis


def init_game():
    load_dotenv(find_dotenv())

    game_scene = textwrap.dedent(  # todo: this text has to be generated by AI
        """In the heart of a bustling mid-west saloon, the air filled with the sound of piano tunes and clinking, \
        glasses a diverse group of individuals finds shelter from a howling snowstorm. Each person, a stranger to the \
        next, carries a story colored by the trials of the Wild West. As the fire crackles in the hearth and the storm \
        rages on, unseen tensions and hidden tales weave a tapestry of intrigue and suspense."""
    )
    print("\nGame Scene:")
    print(game_scene)
    print()

    all_players: Dict[str, Player] = generate_players()
    for current_player_id, current_player in all_players.items():
        print('Create a player:', current_player_id)

        players_names_and_stories = "\n\n".join(
            f"Name: {player.name}\nStory: {player.backstory}"
            for player_id, player in all_players.items() if player_id != current_player_id
        )

        new_player_assistant = PlayerAssistantDecorator.create_player(
            player=current_player,
            game_story=game_scene,
            players_names_and_stories=players_names_and_stories
        )
        current_player.assistant_id = new_player_assistant.assistant.id
        current_player.thread_id = new_player_assistant.thread.id

    new_arbiter = ArbiterAssistantDecorator.create_arbiter(players=list(all_players.values()), game_story=game_scene)

    game = Game(
        id=str(uuid.uuid4()),
        story=game_scene,
        players=all_players,
        arbiter_assistant_id=new_arbiter.assistant.id,
        arbiter_thread_id=new_arbiter.thread.id
    )

    r = connect_to_redis()
    save_game_to_redis(r, game)
    return game.id


# Sequential execution is super slow
def get_welcome_messages_from_all_players(game_id: str):
    load_dotenv(find_dotenv())

    r = connect_to_redis()
    game: Game = load_game_from_redis(r, game_id)
    if not game or not game.players:
        print(f"Game with id {game_id} not found in Redis")
        return

    all_introductions = []
    for player in game.players.values():
        player_assistant = PlayerAssistantDecorator.load_player_by_assistant_id_with_new_thread(
            assistant_id=player.assistant_id, old_thread_id=player.thread_id
        )
        answer = player_assistant.ask("Please introduce yourself to the other players.")
        all_introductions.append(f"{player.name}: {answer}")
    delete_redis_game_history_list(r, game_id)
    add_player_messages_to_redis_list(r, game_id, all_introductions)
    return all_introductions


# This function for local testing only. When deployed to AWS Lambda, it should call other lambdas for each player
# rather than using threads
def get_welcome_messages_from_all_players_async(game_id: str):
    load_dotenv(find_dotenv())

    r = connect_to_redis()
    game: Game = load_game_from_redis(r, game_id)
    if not game or not game.players:
        print(f"Game with id {game_id} not found in Redis")
        return

    def get_player_introduction(player):
        player_assistant = PlayerAssistantDecorator.load_player_by_assistant_id_with_new_thread(
            assistant_id=player.assistant_id, old_thread_id=player.thread_id
        )
        answer = player_assistant.ask("Please introduce yourself to the other players.")
        return f"{player.name}: {answer}"

    with concurrent.futures.ThreadPoolExecutor() as executor:
        futures = [executor.submit(get_player_introduction, player) for player in game.players.values()]
        all_introductions = [future.result() for future in concurrent.futures.as_completed(futures)]

    delete_redis_game_history_list(r, game_id)
    add_player_messages_to_redis_list(r, game_id, all_introductions)
    return all_introductions


def talk_to_all(game_id: str, user_message: str):
    load_dotenv(find_dotenv())
    r = connect_to_redis()
    game: Game = load_game_from_redis(r, game_id)

    arbiter = ArbiterAssistantDecorator.load_arbiter_by_assistant_id_and_thread_id(
        assistant_id=game.arbiter_assistant_id, thread_id=game.arbiter_thread_id
    )
    add_player_messages_to_redis_list(r, game_id, ['User: ' + user_message])  # todo: create some object for the player in the init_game
    last_few_messages: List[str] = read_messages_from_redis(r, game_id, game.current_messages_offset)
    game.current_messages_offset += len(last_few_messages)

    last_few_messages_str = '\n'.join(last_few_messages)
    arbiter_reply = arbiter.ask(last_few_messages_str)
    arbiter_reply_json = json.loads(arbiter_reply)
    reply_obj: ArbiterReply = ArbiterReply(replies=arbiter_reply_json['replies'])

    new_messages = [user_message]
    for name in reply_obj.replies:
        player = game.players.get(name)
        new_messages_str = '\n'.join(new_messages)  # todo: load messages from player.offset from Redis
        message = f"Reply to these few messages from other players:\n{new_messages_str}"
        player_assistant = PlayerAssistantDecorator.load_player_by_assistant_id_and_thread_id(
            assistant_id=player.assistant_id, thread_id=player.thread_id
        )
        player_reply = player_assistant.ask(message)
        # todo: save player reply to Redis
        # todo: update player's offset to the latest
        new_message = f"{player.name}: {player_reply}"
        new_messages.append(new_message)
    add_player_messages_to_redis_list(r, game_id, new_messages)
    save_game_to_redis(r, game)


def delete_assistants_from_openai_and_game_from_redis(game_id: str):
    load_dotenv(find_dotenv())
    r = connect_to_redis()
    game: Game = load_game_from_redis(r, game_id)

    arbiter = ArbiterAssistantDecorator.load_arbiter_by_assistant_id_and_thread_id(
        assistant_id=game.arbiter_assistant_id, thread_id=game.arbiter_thread_id
    )
    arbiter.delete()
    for player in game.players.values():
        if player.assistant_id:
            player_assistant = PlayerAssistantDecorator.load_player_by_assistant_id_and_thread_id(
                assistant_id=player.assistant_id, thread_id=player.thread_id
            )
            player_assistant.delete()
            player.assistant_id = ''
            player.thread_id = ''

    delete_redis_game_history_list(r, game_id)
    delete_game_from_redis(r, game)


def delete_assistants_from_openai_by_name(name: str):
    load_dotenv(find_dotenv())
    RawAssistant.delete_all_by_name(name=name)

